require('dotenv').config({ path: '.env.local' });
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

async function insertKey() {
  // 1. Get the first available company
  const { data: companies, error: compErr } = await supabase.from('companies').select('id').limit(1);
  
  if (compErr || !companies || companies.length === 0) {
    console.error("Error finding a company:", compErr);
    // If no company exists, let's create a dummy one
    const { data: newComp, error: insertCompErr } = await supabase.from('companies').insert({ name: 'Test Vendor Inc' }).select().single();
    if (insertCompErr) return console.error("Could not create test company", insertCompErr);
    companies.push(newComp);
  }

  const company_id = companies[0].id;

  // 2. Insert the test API key
  const { data, error } = await supabase.from('api_keys').insert({
    company_id: company_id,
    key_value: 'qac_test_key_123',
    description: 'Test Webhook Key generated by CLI'
  }).select();

  if (error) {
    console.error('Failed to insert API key:', error);
  } else {
    console.log('✅ Successfully inserted API Key for company:', company_id);
    console.log(data);
  }
}

insertKey();
